In [ ]:
print("hello")

hello


# Creation,indexing, and slicing of numpy arrays

In [2]:
import numpy as np

In [ ]:
list=[1,2,3,4,5]
arr1=np.array(list)
arr2=np.array([5,6,7,8,9])

In [6]:
lst2=[5,6,7,8,9]

In [9]:
print(type(list))
print(type(lst2))

<class 'type'>
<class 'list'>


In [ ]:
import numpy as np
arr3=[30,40,50]
arr4=np.array([[1,2,3],
               [4,5,6]])

print("Addition:")
print(arr3+arr4)

print("Subtraction:")
print(arr4 - arr3)

print("Subtraction:")
print(arr4 * arr3)

print("Division:")
print(arr4 / arr3)

print("Floor Division:")
print(arr4 // arr3)

print("Power:")
print(arr4 ** arr3)


Addition:
[[31 42 53]
 [34 45 56]]
Subtraction:
[[-29 -38 -47]
 [-26 -35 -44]]
Subtraction:
[[ 30  80 150]
 [120 200 300]]
Division:
[[0.03333333 0.05       0.06      ]
 [0.13333333 0.125      0.12      ]]
Floor Division:
[[0 0 0]
 [0 0 0]]
Power:
[[                   1        1099511627776  6048575297968530377]
 [ 1152921504606846976 -4369436395329424031 -8132375027124273152]]
