Task-1.1 basic filtering
create a numpy array ages with the following values:[25,30,18,35,22,40,17].
use boolean indexing to create a new array adults containing only the ages that are 18 or older.

In [ ]:
import numpy as np 

ages = np.array([25,30,18,35,22,40,17])
adults = ages[ages >= 18]

print("ages:", ages)
print("adults:", adults)

ages: [25 30 18 35 22 40 17]
adults: [25 30 18 35 22 40]


Task 1.2: Filtering with Multiple Conditions
Using the ages array again, find the ages that are strictly greater than 20 AND strictly less than 35.
Store the result in a new array called young_adults.

In [3]:
import numpy as np

ages = np.array([10,25,33,40,21,40,17])
young_adults = ages[(ages > 20) & (ages < 35)]

print("Young Adults:", young_adults)

Young Adults: [25 33 21]


Task 1.3: Filtering Strings
Create a NumPy array names with the following values: ['Alice', 'Bob', 'Charlie', 'David', 'Eve'].
Use boolean indexing to select names that start with the letter 'A' or 'E'.
Hint: You might need to use string operations within your boolean condition.

In [9]:
import numpy as np 

names = np.array ( ['Alice', 'Bob', 'Charlie', 'David', 'Eve']) 
mask = np.char.startswith(names, 'A')| np.char.startswith(names, 'E')

selected_names = names[mask]
print("selected_names:", selected_names)

selected_names: ['Alice' 'Eve']


Task 2.1: Basic Masking for Selection
Create a NumPy array temperatures with the following values: [28, 32, 25, 35, 30, 22, 38].
Create a boolean mask is_hot where True indicates temperatures above 30 degrees Celsius.
Use this mask to select the hot temperatures from the temperatures array.

In [10]:
import numpy as np

temperatures = np.array([28, 32, 25, 35, 30, 22, 38])
is_hot = temperatures > 30
hot_temperatures = temperatures[is_hot]

print("Boolean Mask:", is_hot)
print("Hot Temperatures:", hot_temperatures)

Boolean Mask: [False  True False  True False False  True]
Hot Temperatures: [32 35 38]


Task 2.2: Masking for Modification
Using the temperatures array again, use the is_hot mask to change all temperatures above 30 degrees Celsius to 31 degrees Celsius.

In [11]:
import numpy as np

temperatures = np.array([28, 32, 25, 35, 30, 22, 38])
is_hot = temperatures > 30
temperatures[is_hot] = 31

print("Updated Temperatures:", temperatures)

Updated Temperatures: [28 31 25 31 30 22 31]


Task 2.3: Using np.where() for Masking
Create a NumPy array scores with the following values: [65, 80, 72, 90, 55, 78].
Use np.where() to create a new array grades. If a score is 75 or above, the grade should be 'Pass', otherwise 'Fail'.

In [12]:
import numpy as np

scores = np.array([65, 80, 72, 90, 55, 78])
grades = np.where(scores >= 75, 'Pass', 'Fail')

print("Scores:", scores)
print("Grades:", grades)

Scores: [65 80 72 90 55 78]
Grades: ['Fail' 'Pass' 'Fail' 'Pass' 'Fail' 'Pass']


Task 3.1: Reshaping a 1D array to 2D
Create a 1D NumPy array numbers_1d with values from 1 to 12 (inclusive).
Reshape this array into a 2D array with 3 rows and 4 columns.

In [14]:
numbers_1D = np.arange(1,13)
numbers_2D = numbers_1D.reshape(3,4)

print("1D Array:", numbers_1D)
print("2D Array:", numbers_2D)


1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
2D Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Task 3.2: Reshaping a 2D array to 1D (Flattening)
Using the numbers_2d array from the previous task, flatten it back into a 1D array.

In [15]:
numbers_1D = np.arange(1,13)
numbers_2D = numbers_1D.reshape(3,4)

numbers_flat = numbers_2D.flatten()

print("2D array:", numbers_2D)
print("Flattend Array:", numbers_flat)

2D array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattend Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


Task 3.3: Reshaping with -1
Create a 1D NumPy array values with values from 1 to 15 (inclusive).
Reshape this array into a 2D array with 5 rows, letting NumPy automatically determine the number of columns.

In [25]:
values = np.arange(1, 16)

reshaped_values = values.reshape(5,-1)

print(values)
print("reshaped_values: ")
print(reshaped_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
reshaped_values: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


Task 4.1: Broadcasting a Scalar to an Array
Create a NumPy array prices with the following values: [10, 20, 30].
Increase all prices by 5 using broadcasting.

In [ ]:
prices = np.array([10, 20, 30])
new_prices = prices + 5

print("Original Prices:", prices)
print("Updated Prices:", new_prices)

Original Prices: [10 20 30]
Updated Prices: [15 25 35]


Task 4.2: Broadcasting a 1D Array to a 2D Array (Row-wise)
Create a 2D NumPy array sales representing sales figures for 3 products over 2 days:
'''
[[10, 20],
[15, 25],
[12, 18]]
'''
Create a 1D NumPy array bonuses representing bonuses for each product: [2, 3, 1].
Add the bonuses array to the sales array, broadcasting row-wise.

In [28]:
sales = np.array([
    [10, 20],
    [15, 25],
    [12, 18]
])

bonuses = np.array([2, 3, 1])
result = sales + bonuses[:, np.newaxis]

print("Sales:",sales)
print("Bonuses:", bonuses)
print("Updated Sales:",result)

Sales: [[10 20]
 [15 25]
 [12 18]]
Bonuses: [2 3 1]
Updated Sales: [[12 22]
 [18 28]
 [13 19]]


Task 4.3: Broadcasting a 1D Array to a 2D Array (Column-wise)
Using the sales array again, create a 1D NumPy array tax_rates representing tax rates for each day: [0.1, 0.05].
Calculate the tax amount for each sale by multiplying the sales array with the tax_rates array, broadcasting column-wise.

In [29]:
sales = np.array([
    [10, 20],
    [15, 25],
    [12, 18]
])

tax_rates = np.array([0.1, 0.05])
tax_amount = sales * tax_rates

print("Sales:",sales)
print("Tax Rates:", tax_rates)
print("Tax Amount:",tax_amount)

Sales: [[10 20]
 [15 25]
 [12 18]]
Tax Rates: [0.1  0.05]
Tax Amount: [[1.   1.  ]
 [1.5  1.25]
 [1.2  0.9 ]]
