<a href="https://colab.research.google.com/github/mansipanchal22-ml/pythonfirstcode/blob/main/Lab_Work_15-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### **1. Mathematical Operations**

##### 1. Create two NumPy arrays of shape (3, 3) and perform element-wise addition, subtraction, multiplication, and division.

In [1]:
import numpy as np

arr1 = np.array([[10,20,30],
                 [40,50,60],
                 [70,80,90]])

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

print("Addition: ", arr1 + arr2)
print("Subtraction: ", arr1 - arr2)
print("Multiplication: ",arr1 * arr2)
print("Division:",arr1 / arr2)

Addition:  [[11 22 33]
 [44 55 66]
 [77 88 99]]
Subtraction:  [[ 9 18 27]
 [36 45 54]
 [63 72 81]]
Multiplication:  [[ 10  40  90]
 [160 250 360]
 [490 640 810]]
Division: [[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


##### 2. Generate a NumPy array with random integers and apply square root, exponential, and logarithmic functions.

In [4]:
arr = np.random.randint(1, 10, size=5)

print("Original Array:", arr)

sqrt_arr = np.sqrt(arr)
print("Square Root:", sqrt_arr)

exp_arr = np.exp(arr)
print("Exponential:", exp_arr)

log_arr = np.log(arr)
print("Logarithm:", log_arr)

Original Array: [9 7 8 1 3]
Square Root: [3.         2.64575131 2.82842712 1.         1.73205081]
Exponential: [8.10308393e+03 1.09663316e+03 2.98095799e+03 2.71828183e+00
 2.00855369e+01]
Logarithm: [2.19722458 1.94591015 2.07944154 0.         1.09861229]


##### 3. Create a NumPy array and apply trigonometric operations like sin, cos, and tan.

In [5]:
arr = np.array([0, 30, 45, 60, 90])
arr

radians = np.deg2rad(arr)
print("Radians:", radians)

sin_arr = np.sin(radians)
cos_arr = np.cos(radians)
tan_arr = np.tan(radians)

print("Sine:", sin_arr)
print("Cosine:", cos_arr)
print("Tangent:", tan_arr)

Radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


##### 4. Normalize a NumPy array using vectorized operations (subtract mean and divide by std).

In [6]:
arr = np.array([10, 20, 30, 40, 50])

mean = np.mean(arr)
print("Mean:", mean)

std = np.std(arr)
print("Standard Deviation:", std)

normalized_arr = (arr - mean) / std
print("Normalized Array:", normalized_arr)

Mean: 30.0
Standard Deviation: 14.142135623730951
Normalized Array: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


##### 5. Implement a function using NumPy that calculates the Euclidean distance between two points.

In [12]:
import numpy as np

p1 = np.array([1, 2])
p2 = np.array([4, 6])

distance = np.sqrt(np.sum((p2 - p1) ** 2))

print("Euclidean Distance:", distance)

Euclidean Distance: 5.0


#### **2. Combining and Splitting Arrays**

##### 1. Create two 1D arrays and concatenate them horizontally and vertically.

In [13]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

horizontal = np.concatenate((arr1, arr2))
vertical = np.concatenate((arr1, arr2))

print("Array 1:", arr1)
print("Array 2:", arr2)

print("Horizontal:", horizontal)
print("Vertical:", vertical)

Array 1: [1 2 3]
Array 2: [4 5 6]
Horizontal: [1 2 3 4 5 6]
Vertical: [1 2 3 4 5 6]


##### 2. Stack multiple 2D arrays using vstack and hstack and then split them back using vsplit and hsplit.

In [16]:
import numpy as np

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

print("arr1:", arr1)
print("arr2:", arr2)
v_stack = np.vstack((arr1, arr2))
print("VStack:", v_stack)

h_stack = np.hstack((arr1, arr2))
print("HStack:", h_stack)

v_split = np.vsplit(v_stack, 2)
print("VSplit:", v_split)

h_split = np.hsplit(h_stack, 2)
print("HSplit:", h_split)

arr1: [[1 2]
 [3 4]]
arr2: [[5 6]
 [7 8]]
VStack: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
HStack: [[1 2 5 6]
 [3 4 7 8]]
VSplit: [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
HSplit: [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


##### 3. Create a 2D array and split it into 4 equal sub-arrays.

In [20]:
import numpy as np
arr = np.arange(1,17).reshape(4, 4)
print(arr)

result = np.vsplit(arr, 4)

print("4 sub-arrays:")
for i in result:
  print(i)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
4 sub-arrays:
[[1 2 3 4]]
[[5 6 7 8]]
[[ 9 10 11 12]]
[[13 14 15 16]]


##### 4. Demonstrate the difference between concatenate, stack, and hstack functions using 2D arrays.

In [25]:
import numpy as np

arr1 = np.array([[10, 20],
                 [30, 40]])

arr2 = np.array([[50, 60],
                 [70, 80]])

print("Array 1:",arr1)

print("Array 2:",arr2)

# Concatenate row-wise
concat = np.concatenate((arr1, arr2), axis=0)
print("Concatenate:",concat)

# Stack
stack = np.stack((arr1, arr2), axis=0)
print("Stack:",stack)

# Horizontal stack
hstack = np.hstack((arr1, arr2))
print("HStack:",hstack)

Array 1: [[10 20]
 [30 40]]
Array 2: [[50 60]
 [70 80]]
Concatenate: [[10 20]
 [30 40]
 [50 60]
 [70 80]]
Stack: [[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
HStack: [[10 20 50 60]
 [30 40 70 80]]


##### 5. Create a 3D array and flatten it, then reshape it back to its original shape.

In [27]:
import numpy as np

# Create a 3D array
arr = np.array([[[1, 2],
                 [3, 4]],

                [[5, 6],
                 [7, 8]]])

print("3D Array:",arr)

flat = arr.flatten()
print("Flattened Array:",flat)

# Reshape back to original shape
new_arr = flat.reshape(2, 2, 2)
print("Reshaped Array:",new_arr)

3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Flattened Array: [1 2 3 4 5 6 7 8]
Reshaped Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### **3. Search, Sort, Aggregating/Statistical Functions**

##### 1. Create a NumPy array and find the index of the maximum and minimum elements.

In [32]:
import numpy as np
arr = np.array([10,20,5,42,15])

print("array:",arr)

max_index = np.argmax(arr)

min_index = np.argmin(arr)

print("index of max:", max_index)
print("index of min:", min_index)

array: [10 20  5 42 15]
index of max: 3
index of min: 2


##### 2. Sort a 2D array along different axes and display the result.

In [34]:
import numpy as np

arr = np.array([[30, 10, 20],
                [60, 40, 50],
                [90, 70, 80]])

print("Array:",arr)

row_sort = np.sort(arr, axis=1)
print("Sort along rows:",row_sort)

column_sort = np.sort(arr, axis=0)
print("Sort along columns:",column_sort)

Array: [[30 10 20]
 [60 40 50]
 [90 70 80]]
Sort along rows: [[10 20 30]
 [40 50 60]
 [70 80 90]]
Sort along columns: [[30 10 20]
 [60 40 50]
 [90 70 80]]


##### 3. Generate a random NumPy array and find the mean, median, variance, and standard deviation.

In [35]:
arr = np.random.randint(1, 50, 10)

print("Array:", arr)

mean = np.mean(arr)
median = np.median(arr)
variance = np.var(arr)
std = np.std(arr)

print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std)

Array: [21  8 12 10 32 37 14 35 28 35]
Mean: 23.2
Median: 24.5
Variance: 118.96
Standard Deviation: 10.906878563548783


##### 4. Use np.where to find all elements greater than a certain threshold in a given array.

In [37]:
arr = np.array([10, 25, 5, 40, 15, 30, 8])

threshold = 25
result = np.where(arr > threshold)

print("Array:", arr)
print("Elements greater than", threshold, ":", arr[result])

Array: [10 25  5 40 15 30  8]
Elements greater than 25 : [40 30]


##### 5. Create a NumPy array and count how many elements are positive, negative, or zero.

In [40]:
arr = np.array([10, -5, 0, 25, -8, 0, 15, -2])
positive = np.sum(arr > 0)
negative = np.sum(arr < 0)
zero = np.sum(arr == 0)

print("Array:", arr)
print("Positive elements:", positive)
print("Negative elements:", negative)
print("Zero elements:", zero)

Array: [10 -5  0 25 -8  0 15 -2]
Positive elements: 3
Negative elements: 3
Zero elements: 2
