<a href="https://colab.research.google.com/github/mansipanchal22-ml/pythonfirstcode/blob/main/Lab_Work_8_1_%7C_Python_AI_ML_DA_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### **1. Introduction to NumPy**

#### **Task 1**: Import the NumPy library and print its version.

In [3]:
import numpy as np
print(np.__version__)


2.1.3


**Task 2**: Create a one-dimensional NumPy array of integers from 0 to 9 and print it.

In [2]:
arr = np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


**Task 3**: Generate a two-dimensional NumPy array with random values and print its shape and data type.

In [5]:
array = np.random.rand(2,4)
print(array)
print("Shape: ",array.shape)
print("Data TYpe: ",array.dtype)

[[0.51283151 0.2488517  0.94959497 0.32757607]
 [0.22349885 0.10412507 0.04343709 0.2311132 ]]
Shape:  (2, 4)
Data TYpe:  float64


**Task 4**: Create a NumPy array with 50 evenly spaced values between 0 and 10.

In [6]:
num = np.linspace(0,50,3)
print(num)

[ 0. 25. 50.]


**Task 5**: Write a program to demonstrate the difference between a Python list and a NumPy array by performing element-wise addition on both.

In [7]:
#using Python list
lst1 = [10,20,30,40]
lst2 = [50,60,70,80]
result = lst1 + lst2
print("addition of list(concatation): ",result)

#using Numpy array
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
result = arr1+arr2
print("addition of array(elementwise): ",result)


addition of list(concatation):  [10, 20, 30, 40, 50, 60, 70, 80]
addition of array(elementwise):  [ 6  8 10 12]


#### **2. Creation of NumPy Arrays**

**Task 6**: Create a NumPy array of all zeros with a shape of (3, 4).

In [13]:
arr = np.zeros((3,4),dtype=int)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

**Task 7**: Create a NumPy array of all ones with a shape of (2, 5) and a data type of float.

In [12]:
arr = np.ones((2,5),dtype=float)
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**Task 8**: Use `arange()` to create a NumPy array containing numbers from 10 to 50 with a step of 5.

In [15]:
arr = np.arange(10,51,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

**Task 9**: Generate a 3x3 identity matrix using NumPy.

In [16]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Task 10**: Create a 4x4 array filled with random integers between 1 and 20.

In [17]:
arr = np.random.randint(1,21,size=(4,4))
arr

array([[10, 20,  9, 12],
       [19, 11, 15,  5],
       [14,  1,  1,  3],
       [20, 15, 13,  8]])

---

#### **3. Indexing and Slicing of NumPy Arrays**

**Task 11**: Create a 1D NumPy array with values ranging from 1 to 15. Slice the array to extract elements from index 3 to 8.

In [22]:
array = np.arange(1,16)
print("Array:",array)

extract_array = array[2:8]
print("Extract array:")
print(extract_array)

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Extract array:
[3 4 5 6 7 8]


**Task 12**: Generate a 3x3 matrix with values ranging from 1 to 9. Retrieve the element at the second row and third column.

In [23]:
array = np.arange(1,10)
array2 = array.reshape(3,3)
print(array2[1][2])

6


**Task 13**: Slice a 4x4 array to extract the last two rows and the last two columns.

In [24]:
array = np.arange(1,17)
print("Array:",array)

array1 = array.reshape((4,4))
print("Array1:",array1)

array3 = array1[-2:,-2:]
print("Array3:",array3)

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Array1: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Array3: [[11 12]
 [15 16]]


**Task 14**: Create a 5x5 matrix of random integers between 10 and 50. Replace all elements in the first row with the value 100.

In [25]:
array = np.random.randint(10,50,size=(5,5))
print("Origial matrix:")
print(array)

array[0,:]=100
print("Modified matrix:")
print(array)


Origial matrix:
[[33 36 26 23 21]
 [22 31 33 35 12]
 [28 30 12 13 40]
 [35 12 28 21 49]
 [31 41 42 43 37]]
Modified matrix:
[[100 100 100 100 100]
 [ 22  31  33  35  12]
 [ 28  30  12  13  40]
 [ 35  12  28  21  49]
 [ 31  41  42  43  37]]


**Task 15**: Create a 1D NumPy array of 10 elements. Use boolean indexing to filter out all values greater than 5.

In [26]:
8array = np.arange(1,11)
print(array)
filtered_array = array[array<=5]
print(filtered_array)

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5]
